name = "Dory"
uuid = "7810ee48-929a-11e9-02ca-05eb922bb063"
authors = ["Avi <avinash@mis.mpg.de>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
